---
abstract: 'supporting for application process monitoring, as defined by opentracing.io'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '1.124'
  Test::Fatal: '0.010'
  Test::Files: '0.14'
  Test::More: '0.98'
  Test::Refcount: '0.07'
  Test::Warnings: '0.024'
  indirect: '0'
  perl: '5.020'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OpenTracing
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  OpenTracing:
    file: lib/OpenTracing.pm
    version: '0.004'
  OpenTracing::Any:
    file: lib/OpenTracing/Any.pm
    version: '0.004'
  OpenTracing::Batch:
    file: lib/OpenTracing/Batch.pm
    version: '0.004'
  OpenTracing::Common:
    file: lib/OpenTracing/Common.pm
    version: '0.004'
  OpenTracing::DSL:
    file: lib/OpenTracing/DSL.pm
    version: '0.004'
  OpenTracing::Log:
    file: lib/OpenTracing/Log.pm
    version: '0.004'
  OpenTracing::Process:
    file: lib/OpenTracing/Process.pm
    version: '0.004'
  OpenTracing::Span:
    file: lib/OpenTracing/Span.pm
    version: '0.004'
  OpenTracing::SpanContext:
    file: lib/OpenTracing/SpanContext.pm
    version: '0.004'
  OpenTracing::SpanProxy:
    file: lib/OpenTracing/SpanProxy.pm
    version: '0.004'
  OpenTracing::Tag:
    file: lib/OpenTracing/Tag.pm
    version: '0.004'
  OpenTracing::Tracer:
    file: lib/OpenTracing/Tracer.pm
    version: '0.004'
requires:
  Exporter: '0'
  Math::Random::Secure: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
  parent: '0'
  perl: '5.020'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/OpenTracing/issues
  homepage: https://github.com/team-at-cpan/OpenTracing
  repository: https://github.com/team-at-cpan/OpenTracing.git
version: '0.004'
x_authority: cpan:TEAM
x_generated_by_perl: v5.30.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
